# Generated by Django 5.1.2 on 2025-08-13 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
