# Generated by Django 4.2.7 on 2025-09-05 22:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testgroup',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_test_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testassignment',
            name='assigned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testassignment',
            name='student_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_assignments', to='tests.studentgroup'),
        ),
        migrations.AddField(
            model_name='testassignment',
            name='test_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='tests.testgroup'),
        ),
        migrations.AddField(
            model_name='studenttestattempt',
            name='current_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tests.testsection'),
        ),
        migrations.AddField(
            model_name='studenttestattempt',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studenttestattempt',
            name='test_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='tests.testgroup'),
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='student_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.question'),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='section_attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='tests.sectionattempt'),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='selected_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.choice'),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='test_attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='tests.studenttestattempt'),
        ),
        migrations.AddField(
            model_name='sectionattempt',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.testsection'),
        ),
        migrations.AddField(
            model_name='sectionattempt',
            name='test_attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_attempts', to='tests.studenttestattempt'),
        ),
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='tests.testsection'),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='tests.question'),
        ),
        migrations.AlterUniqueTogether(
            name='testassignment',
            unique_together={('test_group', 'student_group')},
        ),
        migrations.AlterUniqueTogether(
            name='studenttestattempt',
            unique_together={('test_group', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='studentgroup',
            unique_together={('name', 'teacher')},
        ),
        migrations.AlterUniqueTogether(
            name='studentanswer',
            unique_together={('test_attempt', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='sectionattempt',
            unique_together={('test_attempt', 'section')},
        ),
    ]
