# Generated by Django 4.2.7 on 2025-09-13 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentanswer',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='studentanswer',
            constraint=models.UniqueConstraint(fields=('test_attempt', 'question'), name='uniq_attempt_question'),
        ),
    ]
